version: "3"

services:
  db:
    container_name: db
    image: mysql:8.1
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=yt_proxy
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./dbdata:/var/lib/mysql
